# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'asking.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Asking_dialog(object):
    def setupUi(self, Asking_dialog):
        Asking_dialog.setObjectName("Asking_dialog")
        Asking_dialog.resize(401, 151)
        Asking_dialog.setMinimumSize(QtCore.QSize(401, 151))
        Asking_dialog.setMaximumSize(QtCore.QSize(401, 151))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Asking_dialog.setWindowIcon(icon)
        Asking_dialog.setStyleSheet("QDialog{\n"
"background-color: #2e2e38;\n"
"}")
        Asking_dialog.setLocale(QtCore.QLocale(QtCore.QLocale.Ukrainian, QtCore.QLocale.Ukraine))
        self.horizontalLayoutWidget = QtWidgets.QWidget(Asking_dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 80, 379, 47))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.asking_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.asking_layout.setContentsMargins(0, 0, 0, 0)
        self.asking_layout.setSpacing(10)
        self.asking_layout.setObjectName("asking_layout")
        self.yesb = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.yesb.setStyleSheet("QPushButton {\n"
"    font: 12pt \"Century Gothic\";\n"
"    color: #f2b824;\n"
"    background-color: #1d1c21;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover{\n"
" color: #f2c44e;\n"
" background-color: #3a3c42;\n"
"}\n"
"QPushButton:pressed {\n"
"color: #eb7b13;\n"
"}")
        self.yesb.setObjectName("yesb")
        self.asking_layout.addWidget(self.yesb)
        self.nob = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.nob.setStyleSheet("QPushButton {\n"
"    font: 12pt \"Century Gothic\";\n"
"    color: #f2b824;\n"
"    background-color: #1d1c21;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover{\n"
" color: #f2c44e;\n"
" background-color: #3a3c42;\n"
"}\n"
"QPushButton:pressed {\n"
"color: #eb7b13;\n"
"}")
        self.nob.setObjectName("nob")
        self.asking_layout.addWidget(self.nob)
        self.asking_label = QtWidgets.QLabel(Asking_dialog)
        self.asking_label.setGeometry(QtCore.QRect(0, 30, 401, 21))
        self.asking_label.setStyleSheet("font: 12pt \"Century Gothic\";\n"
"color: white;\n"
"border: none;")
        self.asking_label.setAlignment(QtCore.Qt.AlignCenter)
        self.asking_label.setObjectName("asking_label")

        self.retranslateUi(Asking_dialog)
        QtCore.QMetaObject.connectSlotsByName(Asking_dialog)

    def retranslateUi(self, Asking_dialog):
        _translate = QtCore.QCoreApplication.translate
        Asking_dialog.setWindowTitle(_translate("Asking_dialog", "Підтвердження"))
        self.yesb.setText(_translate("Asking_dialog", "Так"))
        self.nob.setText(_translate("Asking_dialog", "Ні"))
        self.asking_label.setText(_translate("Asking_dialog", "Ви точно хочете додати новую інформацію?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Asking_dialog = QtWidgets.QDialog()
    ui = Ui_Asking_dialog()
    ui.setupUi(Asking_dialog)
    Asking_dialog.show()
    sys.exit(app.exec_())
