# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'astro_calendar.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.setEnabled(True)
        Dialog.resize(780, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(780, 600))
        Dialog.setMaximumSize(QtCore.QSize(780, 600))
        Dialog.setMouseTracking(False)
        Dialog.setTabletTracking(False)
        Dialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Dialog.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setWindowOpacity(1.0)
        Dialog.setToolTip("")
        Dialog.setAutoFillBackground(False)
        Dialog.setStyleSheet("QDialog{\n"
"background-color: #2e2e38;\n"
"}")
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.Ukrainian, QtCore.QLocale.Ukraine))
        Dialog.setWindowFilePath("")
        Dialog.setInputMethodHints(QtCore.Qt.ImhNone)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 781, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"color: white;\n"
"border: none;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 130, 741, 339))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.keys = QtWidgets.QTextEdit(self.horizontalLayoutWidget_3)
        self.keys.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.keys.setStyleSheet("color: #f2b824;\n"
"background-color: #1d1c21;\n"
"border: 4px solid #f2b824;\n"
"font: 12pt \"Century Gothic\";")
        self.keys.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.keys.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.keys.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.keys.setAcceptRichText(False)
        self.keys.setObjectName("keys")
        self.verticalLayout.addWidget(self.keys)
        self.update = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.update.setStyleSheet("QPushButton {\n"
"    font: 12pt \"Century Gothic\";\n"
"    color: #f2b824;\n"
"    background-color: #1d1c21;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover{\n"
" color: #f2c44e;\n"
" background-color: #3a3c42;\n"
"}\n"
"QPushButton:pressed {\n"
"color: #eb7b13;\n"
"}")
        self.update.setObjectName("update")
        self.verticalLayout.addWidget(self.update)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.calendardate = QtWidgets.QCalendarWidget(self.horizontalLayoutWidget_3)
        self.calendardate.setEnabled(True)
        self.calendardate.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.calendardate.setAutoFillBackground(False)
        self.calendardate.setStyleSheet("background-color: #f2b824;\n"
"font: 12pt \"Century Gothic\";М")
        self.calendardate.setMinimumDate(QtCore.QDate(2021, 1, 1))
        self.calendardate.setGridVisible(False)
        self.calendardate.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendardate.setDateEditEnabled(True)
        self.calendardate.setObjectName("calendardate")
        self.verticalLayout_2.addWidget(self.calendardate)
        self.linedate = QtWidgets.QDateEdit(self.horizontalLayoutWidget_3)
        self.linedate.setMaximumSize(QtCore.QSize(16777215, 21))
        self.linedate.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.linedate.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.linedate.setStyleSheet("color: #f2b824;\n"
"background-color: #1d1c21;\n"
"border: none;\n"
"font: 12pt \"Century Gothic\";")
        self.linedate.setWrapping(False)
        self.linedate.setAlignment(QtCore.Qt.AlignCenter)
        self.linedate.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.linedate.setProperty("showGroupSeparator", False)
        self.linedate.setMinimumDate(QtCore.QDate(2021, 1, 1))
        self.linedate.setCalendarPopup(False)
        self.linedate.setObjectName("linedate")
        self.verticalLayout_2.addWidget(self.linedate)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.newslabel = QtWidgets.QLabel(Dialog)
        self.newslabel.setGeometry(QtCore.QRect(0, 490, 779, 39))
        self.newslabel.setStyleSheet("font: 12pt \"Century Gothic\";\n"
"color: white;\n"
"border: none;")
        self.newslabel.setAlignment(QtCore.Qt.AlignCenter)
        self.newslabel.setObjectName("newslabel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, 540, 781, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.movelink = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.movelink.setMinimumSize(QtCore.QSize(120, 0))
        self.movelink.setMaximumSize(QtCore.QSize(250, 16777215))
        self.movelink.setStyleSheet("QPushButton {\n"
"    font: 12pt \"Century Gothic\";\n"
"    color: #f2b824;\n"
"    background-color: #1d1c21;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover{\n"
" color: #f2c44e;\n"
" background-color: #3a3c42;\n"
"}\n"
"QPushButton:pressed {\n"
"color: #eb7b13;\n"
"}")
        self.movelink.setObjectName("movelink")
        self.horizontalLayout.addWidget(self.movelink)
        self.nextevent = QtWidgets.QLabel(Dialog)
        self.nextevent.setGeometry(QtCore.QRect(0, 60, 779, 39))
        self.nextevent.setStyleSheet("font: 12pt \"Century Gothic\";\n"
"color: white;\n"
"border: none;")
        self.nextevent.setAlignment(QtCore.Qt.AlignCenter)
        self.nextevent.setObjectName("nextevent")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Астрономічний календар"))
        self.label.setText(_translate("Dialog", "Астрономічний календар (2021-2022) за даними kuryliak.pp.ua"))
        self.keys.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Century Gothic\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.update.setText(_translate("Dialog", "Оновити"))
        self.calendardate.setWhatsThis(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.newslabel.setText(_translate("Dialog", "Остання новина"))
        self.movelink.setText(_translate("Dialog", "Детальніше"))
        self.nextevent.setText(_translate("Dialog", "До наступної події залишилось:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
